# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: noun.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='noun.proto',
  package='verbanoun',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nnoun.proto\x12\tverbanoun\"\x1f\n\x0bNounRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"\x1c\n\x0cNounResponse\x12\x0c\n\x04noun\x18\x01 \x01(\t2H\n\x04Noun\x12@\n\x0bProvideNoun\x12\x16.verbanoun.NounRequest\x1a\x17.verbanoun.NounResponse\"\x00\x62\x06proto3')
)




_NOUNREQUEST = _descriptor.Descriptor(
  name='NounRequest',
  full_name='verbanoun.NounRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='verbanoun.NounRequest.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=56,
)


_NOUNRESPONSE = _descriptor.Descriptor(
  name='NounResponse',
  full_name='verbanoun.NounResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='noun', full_name='verbanoun.NounResponse.noun', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['NounRequest'] = _NOUNREQUEST
DESCRIPTOR.message_types_by_name['NounResponse'] = _NOUNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NounRequest = _reflection.GeneratedProtocolMessageType('NounRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOUNREQUEST,
  '__module__' : 'noun_pb2'
  # @@protoc_insertion_point(class_scope:verbanoun.NounRequest)
  })
_sym_db.RegisterMessage(NounRequest)

NounResponse = _reflection.GeneratedProtocolMessageType('NounResponse', (_message.Message,), {
  'DESCRIPTOR' : _NOUNRESPONSE,
  '__module__' : 'noun_pb2'
  # @@protoc_insertion_point(class_scope:verbanoun.NounResponse)
  })
_sym_db.RegisterMessage(NounResponse)



_NOUN = _descriptor.ServiceDescriptor(
  name='Noun',
  full_name='verbanoun.Noun',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=160,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProvideNoun',
    full_name='verbanoun.Noun.ProvideNoun',
    index=0,
    containing_service=None,
    input_type=_NOUNREQUEST,
    output_type=_NOUNRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NOUN)

DESCRIPTOR.services_by_name['Noun'] = _NOUN

# @@protoc_insertion_point(module_scope)
