# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='verb.proto',
  package='verbanoun',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nverb.proto\x12\tverbanoun\"\x1f\n\x0bVerbRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"\x1c\n\x0cVerbResponse\x12\x0c\n\x04verb\x18\x01 \x01(\t2H\n\x04Verb\x12@\n\x0bProvideVerb\x12\x16.verbanoun.VerbRequest\x1a\x17.verbanoun.VerbResponse\"\x00\x62\x06proto3')
)




_VERBREQUEST = _descriptor.Descriptor(
  name='VerbRequest',
  full_name='verbanoun.VerbRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='verbanoun.VerbRequest.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=56,
)


_VERBRESPONSE = _descriptor.Descriptor(
  name='VerbResponse',
  full_name='verbanoun.VerbResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verb', full_name='verbanoun.VerbResponse.verb', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['VerbRequest'] = _VERBREQUEST
DESCRIPTOR.message_types_by_name['VerbResponse'] = _VERBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerbRequest = _reflection.GeneratedProtocolMessageType('VerbRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERBREQUEST,
  '__module__' : 'verb_pb2'
  # @@protoc_insertion_point(class_scope:verbanoun.VerbRequest)
  })
_sym_db.RegisterMessage(VerbRequest)

VerbResponse = _reflection.GeneratedProtocolMessageType('VerbResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERBRESPONSE,
  '__module__' : 'verb_pb2'
  # @@protoc_insertion_point(class_scope:verbanoun.VerbResponse)
  })
_sym_db.RegisterMessage(VerbResponse)



_VERB = _descriptor.ServiceDescriptor(
  name='Verb',
  full_name='verbanoun.Verb',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=160,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProvideVerb',
    full_name='verbanoun.Verb.ProvideVerb',
    index=0,
    containing_service=None,
    input_type=_VERBREQUEST,
    output_type=_VERBRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VERB)

DESCRIPTOR.services_by_name['Verb'] = _VERB

# @@protoc_insertion_point(module_scope)
