# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import verb_pb2 as verb__pb2


class VerbStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProvideVerb = channel.unary_unary(
        '/verbanoun.Verb/ProvideVerb',
        request_serializer=verb__pb2.VerbRequest.SerializeToString,
        response_deserializer=verb__pb2.VerbResponse.FromString,
        )


class VerbServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ProvideVerb(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VerbServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProvideVerb': grpc.unary_unary_rpc_method_handler(
          servicer.ProvideVerb,
          request_deserializer=verb__pb2.VerbRequest.FromString,
          response_serializer=verb__pb2.VerbResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'verbanoun.Verb', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
